e_shop/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns
from product.views import selectlanguage
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('selectlanguage', selectlanguage, name="selectlanguage"),
    path('i18n/', include("django.conf.urls.i18n")),
]

urlpatterns += i18n_patterns(
    path(_('admin/'), admin.site.urls),
	path('', include('home.urls')),
    path('', include('product.urls')),
    path('', include('user.urls')),
    path('', include('newsletters.urls')),
    #path('', include('newsletter.urls')),
    path('order/', include('order.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    prefix_default_language=False,
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

## APPLICATIONS

home/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
	path('', views.index, name = 'home'),
	path('about-us/', views.aboutus, name = 'about_us'),
	path('contact-us/', views.contactus, name = 'contact-us'),
	path('categorie/<int:id>/<slug:slug>', views.product_categorie, name = 'product_categorie'),
	path('search/', views.search, name = 'search'),
	path('shop-cart/', views.shop_cart, name = 'shop-cart'),
	path('search_auto/', views.search_auto, name = 'search_auto'),
	path('Articles/<int:id>/<slug:slug>', views.product_details, name = 'product_details'),
	path('faq', views.faq, name = 'faq'),

	path('ajaxcolor', views.ajaxcolors, name='ajaxcolor'),
]

order/urls.py
from django.urls import path

from .import views
app_name = 'order'
urlpatterns = [
	
   path('', views.index, name="index"),
   path('add-to-shop-cart/<int:id>', views.add_to_shop_cart, name="add-to-shop-cart"),
   path('delete-from-shop-cart/<int:id>', views.delete_to_shop_cart, name="delete-from-shop-cart"),
   path('orderproduit/', views.orderproduit, name="orderproduit"),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Produit, Variant


# Create your models here.

class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    produit = models.ForeignKey(Produit, on_delete=models.SET_NULL, null=True)
    variant = models.ForeignKey(Variant, on_delete=models.SET_NULL, blank=True ,null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return (self.produit.titre)

    @property
    def price(self):
        return (self.produit.price)

    @property
    def amount(self):
        return (self.produit.price * self.quantity)

    @property
    def varamount(self):
        return (self.quantity * self.produit.price)


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShopping', 'OnShopping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    #email = models.EmailField()
    phone = models.CharField(blank=True, max_length=50)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=150)
    country = models.CharField(blank=True, max_length=150)
    total = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=150)

    date_add = models.DateTimeField(auto_now_add=True)
    date_upd = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'commande'
        verbose_name_plural = 'Commandes'

    def __str__(self):
        return self.user.first_name

class OrderProduit(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    produit = models.ForeignKey(Produit, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.IntegerField()
    amount = models.IntegerField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    
    date_add = models.DateTimeField(auto_now_add=True)
    date_upd = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'commande produit'
        verbose_name_plural = 'Commandes Produits'

    def __str__(self):
        return self.produit.titre


    

    

order/forms.py
from django import forms
from .models import ShopCart, Order

class ShopCartForm(forms.ModelForm):

    class Meta:
        model = ShopCart
        fields = (
            'quantity',
        )

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','address', 'phone','city','country',]

order/views.py
from django.shortcuts import render
from django.contrib import messages
from  django.utils.crypto import get_random_string
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from .models import ShopCart, Order, OrderProduit
from .forms import ShopCartForm, OrderForm
from product.models import Category, Produit, Variant
from user.models import UserProfile

from django.core.mail import send_mail
from django.conf import settings

# Create your views here.

def index(request):

    return HttpResponse('hello order')


@login_required(login_url='/login') #verifie si le client est connecté 
def add_to_shop_cart(request, id): #Ajout du produit dans le panier

    url = request.META.get('HTTP_REFERER')
    current_user = request.user #Accède auxs essions de user

    checkoutproduit = ShopCart.objects.filter(produit_id=id) #Verifie si ShopCart(panier) contient des produits
    if checkoutproduit: #Condition de verification si le panier est vide
        control = 1 # Le paner contient des produits
    else:
        control = 0 #il ny a pas de produit dans le panier

    if request.method=='POST':
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control ==1: #On modifie notre ShopCart (si vraiment y a un produit)
                data = ShopCart.objects.get(produit_id=id) #on initialise "data"
                data.quantity += form.cleaned_data['quantity'] #On ajout le produit 
                data.save() #enregistrer le produit dans shopcart
            else: #le produit n'exist pas dans le panier, donc on ajoute le produit
                data = ShopCart() #On inilialise le ShopCart
                data.user_id = current_user.id
                data.produit_id =id
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, 'Votre produit a été ajouté avec succès !!')
        return HttpResponseRedirect(url)

    else: # s il n y a pas de post
        if control == 1:
            data = ShopCart.objects.get(produit_id=id)
            data.quantity += 1
            data.save()
        else:
            data = ShopCart()
            data.user_id = current_user.id
            data.produit_id=id
            data.quantity = 1
            data.save()
        messages.success(request, 'Votre article  a été ajouté avec success !!')
        return HttpResponseRedirect(url)


@login_required(login_url='/login') #verifie si le client est connecté 
def delete_to_shop_cart(request, id): #Ajout du produit dans le panier

    ShopCart.objects.filter(id=id).delete()
    messages.success(request, 'Votre article a été supprimé .')
    return HttpResponseRedirect('/shop-cart')

def orderproduit(request):
    categorie = Category.objects.all()
    current_user = request.user
    schopcart = ShopCart.objects.filter(user_id=current_user.id)

    total = 0
    for sp in schopcart:
        if sp.produit.variant == 'None':
            total += sp.produit.price * sp.quantity
        else:
            total += sp.variant.price * sp.quantity

    if request.method=='POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            data = Order()
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.country = form.cleaned_data['country']
            data.user_id =current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(5).upper()
            data.code = ordercode
            data.save() 

            subject = "Validation de votre Achat sur Tshop"
            from_email = settings.EMAIL_HOST_USER
            to_email = [current_user.email]
            body = "Félicitation vous venez de valider votre achat sur https://e-trashop.herokuapp.com \n Voici la reference de votre produit {} Nous vous enverons un email".format(ordercode)
            send_mail(subject=subject, from_email=from_email, recipient_list=to_email, message=body, fail_silently=False)


            #Move the ShopCart items to Orders Product items
            schopcart = ShopCart.objects.filter(user_id=current_user.id)
            for sp in schopcart:
                details = OrderProduit()
                details.order_id= data.id #Order id
                details.produit_id = sp.produit_id
                details.user_id = current_user.id
                details.quantity = sp.quantity
                if sp.produit.variant == 'None':
                    details.price = sp.produit.price
                else:
                    details.price = sp.variant.price

                details.variant_id = sp.variant_id
                details.amount = sp.amount
                details.save()

                #Reduce quantity of sold produit  from amount of produit
                if sp.produit.variant == 'None':
                    produit = Produit.objects.get(id=sp.produit_id)
                    produit.amount -= sp.quantity
                    produit.save()
                else:
                    variant = Variant.objects.get(id=sp.produit_id)
                    variant.amount -= sp.quantity
                    variant.save()
            
            ShopCart.objects.filter(user_id = current_user.id).delete() #Supprime les produit dans shopcart
            request.session['cart_items']=0
            messages.success(request, 'Your has been completed, thank you')
            return render(request, 'pages/order-completed.html', {'ordercode':ordercode, 'categorie':categorie})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect('/order/orderproduit')

    form = OrderForm()
    profile = UserProfile.objects.get(user_id= current_user.id)
    schopcart = ShopCart.objects.filter(user_id=current_user.id)
    context = {'schopcart':schopcart,
        'categorie':categorie,
        'total':total,
        'form':form,
        'profile':profile,
        }
    return render(request, 'pages/order-form.html', context)
	
	

	
	
		
	

	

    

templates/pages/aboutus.html
{% extends 'bases/base.html' %}

{% block title %} About Us- {{setting.titre}} {% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keywords}} {% endblock %}

{% block sidebar %} {% include 'pages/sidebar.html' %} {% endblock  %}

{% block body %} 

     <!-- BREADCRUMB -->
     <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">About Us </li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                {{setting.aboutus|safe}}
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock  %}

templates/pages/color_list.html
<input type="hidden" name="size" id="size" value="{{size_id}}">
<ul class="color-option">
    <li><span class="text-uppercase">Color:</span></li>
    {% for rs in colors %}
        <input type="radio" name="variantid" id="variantid" value="{{ rs.id }}" onchange="this.form.submit();">
        <li>
            <a href="#" style='background-color:"{{ rs.color.code }}"; color: #D9D9D9; text-shadow: 1px 1px #000000; width: 70px'>
                {{rs.color}} {{rs.price}} €
            </a>
            {% if photo %}
            <img src="{{rs.photo}}" style="height: 70px;">
            {% endif 
                %}
        </li>
    {% endfor %}

</ul>

templates/pages/contactus.html
{% extends 'bases/base.html' %}

{% block title %} Contact Us- {{setting.titre}} {% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keywords}} {% endblock %}

{% block sidebar %} {% include 'pages/sidebar.html' %} {% endblock  %}

{% block body %} 

     <!-- BREADCRUMB -->
     <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">About Us </li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				
					<div class="col-md-4">
                        
						<div class="billing-details">
							
							<div class="section-title">
                                <h3 class="title">Contact Form  </h3>
                                
                                {% if messages %}
                                    {% for message in messages %}
                                        <div class="alert-alert-{{message.tags}}" role="alert" style="color: darkgreen; font-style: oblique;">
                                            {{message}}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <form id="checkout-form" class="clearfix" method="post">
                                {% csrf_token %}
                                {{form.as_p}} 
                                <input type="submit" value="Envoyer">                
                            </form>
                        </div>
					</div>
                
					<div class="col-md-8">
						<div class="shiping-methods">
							<div class="section-title">
								<h4 class="title">Shiping Methods</h4>
							</div>
							<div class="input-checkbox">
								<div>
                                    {{setting.contactus|safe}}
                                </div>
							</div>
						</div>
					</div>

					
				
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->


{% endblock  %}

templates/pages/faq.html
{% extends 'bases/base.html' %}

{% block title %} Question Frequemment Posées  {% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keywords}} {% endblock %}

{% block sidebar %} {% include 'pages/sidebar.html' %} {% endblock  %}



{% block body %} 

     <!-- BREADCRUMB -->
     <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">Question Fréquement Posées </li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div id="accordion">

                    {% for fa in faq %}
                    <h3>{{fa.question}}</h3>
                    <div>
                      <p>
                        {{fa.answer|safe}}
                      </p>
                    </div>
                    {% endfor %}
                </div>
                
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock  %}

templates/pages/index.html
{% extends 'bases/base.html' %}

{% block title %} {{setting.titre}} {% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keywords}} {% endblock %}

{% block sidebar %} {% include 'pages/sidebar.html' %} {% endblock  %}
{% block slider %} {% include 'pages/slider.html' %} {% endblock  %}
{% block body %} {% include 'pages/content.html' %} {% endblock  %}

templates/pages/order-completed.html
{% extends 'bases/base.html' %}

{% block title %}  Finalisation d'achat {% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keywords}} {% endblock %}

{% block sidebar %} {% include 'pages/sidebar.html' %} {% endblock  %}

{% block body %} 

     <!-- BREADCRUMB -->
     <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">Valider mon achat</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-12">
                    <div class="order-summary-clearfix">
                        <div class="section-title">
                            <h3>Validation de  Commande</h3>
                        </div>
                        <hr>
                         <p>Monsieur/Madame:</p><h3> {{user.first_name}} {{user.last_name}} </h3>
                        <hr>
                        <h4>Votre  Commande est Validé </h4>
                       <h3>Référence du produit: <span style="color: darkorange;"> {{ ordercode }} </span> </h3>
                        <h3>Merci!! </h3> 
                        <h6>Dans 24h on vous livrera votre commande!!</h6>
                        <hr>
                    
                    </div>
                    <div class="pull-right">
                        <a href="/" class="primary-btn float-rigth ml-2" style="margin-right: 10px;">Retour a l' accueil</a>
                    </div>
                </div>

                
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock  %}

templates/pages/order-form.html
{% extends 'bases/base.html' %}

{% block title %}  valider mon achat {{setting.titre}} {% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keywords}} {% endblock %}

{% block sidebar %} {% include 'pages/sidebar.html' %} {% endblock  %}

{% block body %} 

     <!-- BREADCRUMB -->
     <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">Order  </li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <div class="billing-details">
                            <div class="section-title">
                                <h4>Shippiung Details</h4>
                            </div>
                            <p>
                                <label for="id_first_name">Nom:</label>
                                <input type="text" name="first_name" id="first_name" value="{{user.first_name}}" class="input" maxlength="20", required='True'>
                            </p>
                            <p>
                                <label for="id_last_name">Prenom:</label>
                                <input type="text" name="last_name" id="last_name" value="{{user.last_name}}" class="input" maxlength="20", required>
                            </p>
                            <p>
                                <label for="id_address">Adress:</label>
                                <input type="text" name="address" id="address" value="{{profile.address}}" class="input" maxlength="150", required>
                            </p>
                            <p>
                                <label for="id_phone">Phone:</label>
                                <input type="text" name="phone" id="phone" value="{{profile.phone}}" class="input" maxlength="20", required='True'>
                            </p>
                            <p>
                                <label for="id_city">city:</label>
                                <select name="city" id="city" class="input">
                                    <option value="{{profile.city}}" selected>{{profile.city}}</option>
                                    <option value="Abidjan" selected>Abidjan</option>
                                    <option value="Bassam" selected>Bassam</option>
                                    <option value="Alepe" selected>Alepe</option>
                                    <option value="Azope" selected>Azope</option>
                                    <option value="Soubre" selected>Soubre</option>
                                    <option value="Zangou" selected>Zangou</option>
                                    <option value="Korhogo" selected>Korhogo</option>
                                    <option value="Boundiali" selected>Boundiali</option>
                                    <option value="Odiene" selected>Odiéné</option>
                                    
                                </select>
                            </p>
                            <p>
                                <label for="id_country">Country:</label>
                                <input type="text" class="input" name="country" id="country" value="{{profile.country}}" >
                            </p>
                            <div class="pull-right">
                                <button type="submit" class="primary-btn">Valider</button>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="shipping-methods">
                            <div class="section-title">
                                <h4>Payment Informations</h4>
                            </div>
                            <p>
                                <label for="id_first_name">Total:</label>
                                <input type="text" class="input" name="total" readonly value="{{total}}€">
                            </p>
                            <p>
                                <label for="id_first_name">Credit Cart Holder</label>
                                <input type="text" class="input" name="holder" value="">
                            </p>
                            <p>
                                <label for="id_first_name">Credit Cart Number</label>
                                <input type="text" class="input" name="number"  value="">
                            </p>
                            <p>
                                <label for="id_first_name">Credit Exp Date/Year</label>
                                <input type="text" class="input" name="ecpdate"  placeholder="mm/yy">
                            </p>
                            <p>
                                <label for="id_first_name">Security Number</label>
                                <input type="text" class="input" name="secnumber"  value="">
                            </p>
                        </div>
                        <br><br>
                    </div>
                    
                </form>
                
        
                    <div class="col-md-12">
                        <div class="order-summary-clearfix">
                            <div class="section-title">
                                <h3>Product List</h3>
                            </div>
                            
                            <table class="shopping-cart-table table">
                    
                    
                                <thead>
                                    
                                    <tr>
                                        <!-- <th>x</th> -->
                                        <th>Product List</th>
                                        <th></th>
                                        <th class="text-center">Price</th>
                                        <th class="text-center">Quantity</th>
                                        <th class="text-center">Total</th>
                                       
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for sp in schopcart %}
                                    <tr>
                                        <!-- <td>{{forloop.counter}}</td> -->
                                        <td class="thumb"><img src="{{sp.produit.photo.url}}" alt=""></td>
                                        <td class="details">
                                            <a href="/Articles/{{sp.produit.id}}/{{sp.produit.slug}}">{{sp.produit}}</a>
                                        </td>
                                        <td class="price text-center">
                                            <strong>
                                                {% if rs.produit.variant == 'None' %}
                                                    {{sp.produit.price}}
                                                {% else %}
                                                    {{rs.variant.price}}
                                                {% endif %}
                                                
                                            €</strong><br>
                                            <del class="font-weak"><small>{{sp.produit.reduction}}</small>
                                            </del>
                                        </td>
                                        <td class="total text-center"><strong class="primary-color">{{sp.quantity}}</strong></td>
                                        <td class="total text-center">
                                            <strong class="primary-color">
                                                {% if rs.produit.variant == 'None' %}
                                                    {{sp.amount}}
                                                {% else %}
                                                    {{rs.varamount}}
                                                {% endif %}
                                            </strong>
                                        </td>

                                        <!-- <td class="price text-center"><strong>{{sp.produit.price}}</strong><br><del class="font-weak"><small>{{sp.produit.reduction}}</small></del></td>
                                        <td class="total text-center"><strong class="primary-color">{{sp.quantity}}</strong></td>
                                        <td class="total text-center"><strong class="primary-color">{{sp.amount}}€</strong></td> -->
                                    </tr>
                                    {% endfor %}
                                    
                                       
                                <tfoot>
                                    <tr>
                                        <th class="empty" colspan="3"></th>
                                        <th>SUBTOTAL</th>
                                        <th colspan="2" class="sub-total">{{total}}€</th>
                                    </tr>
                                    <tr>
                                        <th class="empty" colspan="3"></th>
                                        <th>SHIPING</th>
                                        <td colspan="2">Free Shipping</td>
                                    </tr>
                                    <tr>
                                        <th class="empty" colspan="3"></th>
                                        <th>TOTAL</th>
                                        <th colspan="2" class="total">{{total}}€</th>
                                    </tr>
                                </tfoot>
                            </table>

                        </div>
                    </div>

                
                
                
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock  %}

templates/pages/sidebar.html
{% load static %}

<!-- NAVIGATION -->
	<div id="navigation">
		<!-- container -->
		<div class="container">
			<div id="responsive-nav">
				{% if page %}
				<!-- category nav -->
				<div class="category-nav">
				{% else %}
				<div class="category-nav show-on-click">
				{% endif %}
					<span class="category-header">Categories <i class="fa fa-list"></i></span>
					{% load myapptags %}
					{% categorylist as categorie %}

					{% load mptt_tags %}
					<ul class="category-list">
						{% recursetree categorie %}
						<li class="dropdown side-dropdown">
							<a href="categorie/{{node.id}}/{{node.slug}}" class="dropdown-toggle" {% if not node.is_leaf_node %} data-toggle="dropdown" aria-expanded="true" {% endif %}>{{node.titre}}<i class="fa fa-angle-right"></i></a>
							<div class="custom-menu">
								<div class="row">
									<div class="col-md-4">
										{% if not node.is_leaf_node %}
										<ul class="list-links">

											<hr>
												{{ children }}
										</ul>
										{% endif %}
										<hr class="hidden-md hidden-lg">
									</div>
								</div>
							</div>
						</li>
						{% endrecursetree %}
						
					</ul>
				</div>
				<!-- /category nav -->

				<!-- menu nav -->
				<div class="menu-nav">
					<span class="menu-header">Menu <i class="fa fa-bars"></i></span>
					<ul class="menu-list">
						<li><a href=" {% url 'home' %} ">Home</a></li>
						<li><a href=" {% url 'about_us' %} ">about us</a></li>
						<li><a href=" {% url 'faq' %}  ">Faqs</a></li>
					
						<li><a href=" {% url 'contact-us' %} ">Contact</a></li>
					</ul>
				</div>
				<!-- menu nav -->
			</div>
		</div>
		<!-- /container -->
	</div>
	<!-- /NAVIGATION -->