e_shop/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns
from product.views import selectlanguage
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('selectlanguage', selectlanguage, name="selectlanguage"),
    path('i18n/', include("django.conf.urls.i18n")),
]

urlpatterns += i18n_patterns(
    path(_('admin/'), admin.site.urls),
	path('', include('home.urls')),
    path('', include('product.urls')),
    path('', include('user.urls')),
    path('', include('newsletters.urls')),
    #path('', include('newsletter.urls')),
    path('order/', include('order.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    prefix_default_language=False,
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

## APPLICATIONS

home/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
	path('', views.index, name = 'home'),
	path('about-us/', views.aboutus, name = 'about_us'),
	path('contact-us/', views.contactus, name = 'contact-us'),
	path('categorie/<int:id>/<slug:slug>', views.product_categorie, name = 'product_categorie'),
	path('search/', views.search, name = 'search'),
	path('shop-cart/', views.shop_cart, name = 'shop-cart'),
	path('search_auto/', views.search_auto, name = 'search_auto'),
	path('Articles/<int:id>/<slug:slug>', views.product_details, name = 'product_details'),
	path('faq', views.faq, name = 'faq'),

	path('ajaxcolor', views.ajaxcolors, name='ajaxcolor'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
	path('moncompte', views.index, name = 'moncompte'),
	path('login/', views.login_in, name = 'login'),
	path('logout/', views.logout_func, name = 'logout'),
	path('signup/', views.signup_form, name = 'signup'),
	path('Update-profile/', views.update_profile, name = 'Update-profile'),
	path('user/password', views.user_password, name = 'user_password'),
	#Panel url
	path('user/produits', views.user_orders, name = 'produits'),
	path('user/order-details/<int:id>', views.user_orderdetail, name = 'user_orderdetail'),
	path('orderproduct', views.user_orderproduct, name = 'orderproduct'),
	path('order-product-details/<int:id>/<int:oid>', views.user_order_product_detail, name = 'user_order_product_detail'),

	path('user/comments', views.user_comments, name = 'comments'),
	path('user/delete-comment/<int:id>', views.user_comments_delete, name = 'user_comments_delete'),
	
	
]

templates/bases/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title> {% block title %} {{setting.titre}} {% endblock %} </title>
		<meta name="keywords" content="{% block keywords %} {{setting.keywords}} {% endblock %} ">
		<meta name="description" content="{% block description %} {{setting.description}} {% endblock %} ">

		<link href="https://fonts.googleapis.com/css?family=Hind:400,700" rel="stylesheet">
		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
		<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}" />
		<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}" />
		<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />

		<!-- <script src=" https://oss.maxcdn.com/htm5shiv/3.7.3/htm5shiv.min.js"></script>
		<script src=" https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script> -->


		<script src=" https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
		
      
	</head>

	<body>
		<header>
			{% include 'bases/nav.html' %}
		</header>

		{% block sidebar %} {% endblock%}

		{% block slider %} {% endblock%}

		{% block body %} {% endblock%}

		
		
		<footer>
			{% include 'bases/footer.html' %}
		</footer>

	</body>
</html>

templates/bases/footer.html
{% load static %}
<!-- FOOTER -->
	<footer id="footer" class="section section-grey">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- footer widget -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<!-- footer logo -->
						<div class="footer-logo">
							<a class="logo" href="#">
		            <img src="{% static 'img/logo.png' %}" alt="">
		          </a>
						</div>

						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p>

						<!-- footer social -->
						<ul class="footer-social">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
						</ul>
						<!-- /footer social -->
					</div>
				</div>
				<!-- /footer widget -->

				<!-- footer widget -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<h3 class="footer-header">My Account</h3>
						<ul class="list-links">
							<li><a href="#">My Account</a></li>
							<li><a href="#">My Wishlist</a></li>
							<li><a href="#">Compare</a></li>
							<li><a href="#">Checkout</a></li>
							<li><a href="#">Login</a></li>
						</ul>
					</div>
				</div>
				<!-- /footer widget -->

				<div class="clearfix visible-sm visible-xs"></div>

				<!-- footer widget -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<h3 class="footer-header">Customer Service</h3>
						<ul class="list-links">
							<li><a href="#">About Us</a></li>
							<li><a href="#">Shiping & Return</a></li>
							<li><a href="#">Shiping Guide</a></li>
							<li><a href="#">FAQ</a></li>
						</ul>
					</div>
				</div>
				<!-- /footer widget -->

				<!-- footer subscribe -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<h3 class="footer-header">Stay Connected</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
						<form method="post" >
							{% csrf_token %}
							{{form1.as_p}}
							<input class="btn btn-danger"  type="submit" value="Envoyer">
						</form>
					</div>
				</div>
				<!-- /footer subscribe -->
			</div>
			<!-- /row -->
			<hr>
			<!-- row -->
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<!-- footer copyright -->
					<div class="footer-copyright">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</div>
					<!-- /footer copyright -->
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</footer>
	<!-- /FOOTER -->
	<!-- <script>
		$(function() {
		$( "#accordion" ).accordion();
		});
	</script> -->

	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/slick.min.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

templates/bases/nav.html
{% load static %}

{% load i18n %}

<header>
		<!-- top Header -->
		<div id="top-header">
			<div class="container">
				<div class="pull-left">
					<span>{% trans "Welcome to E-shop!" %}</span>
					{% if messages %}
						{% for message in messages %}
							<div class="alert-alert-{{message.tags}}" role="alert" style="color: green; font-style: italic;">
								{{message|safe}}
							</div>
						{% endfor %}
					{% endif %}
				</div>
				<div class="pull-right">
					<ul class="header-top-links">
						<!-- <li><a href="#">Store</a></li>
						<li><a href="#">Newsletter</a></li> -->
						<li><a href=" {% url 'faq' %} ">{% trans "Faq" %}</a></li>
						<li class="dropdown default-dropdown">
							<form action=" {% url 'selectlanguage' %} " method="post">
								{% csrf_token %}
								<input type="hidden" name="text"  value="{{redirect_to}}">
								<select name="language" >
									{% get_current_language as LANGUAGE_CODE %}
									{% get_available_languages as LANGUAGES %}
									{% get_language_info_list for LANGUAGES as languages %}

									{% for language in languages %}
									<option value="{{language.code}}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
										{{language.name_local}} ({{language.code}})
									</option>
									{% endfor %}
									<input type="submit" value="OK">
								</select>
							</form>
							<!-- <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">ENG <i class="fa fa-caret-down"></i></a>
							<ul class="custom-menu">
								<li><a href="#">English (ENG)</a></li>
								<li><a href="#">Russian (Ru)</a></li>
								<li><a href="#">French (FR)</a></li>
								<li><a href="#">Spanish (Es)</a></li>
							</ul> -->
						</li>
						<li class="dropdown default-dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">USD <i class="fa fa-caret-down"></i></a>
							<ul class="custom-menu">
								<li><a href="#">USD ($)</a></li>
								<li><a href="#">EUR (€)</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<!-- /top Header -->

		<!-- header -->
		<div id="header">
			<div class="container">
				<div class="pull-left">
					<!-- Logo -->
					<div class="header-logo">
						<a class="logo" href=" {% url 'home' %} ">
							<img src="{% static 'img/logo.png' %}" alt="">
						</a>
					</div>
					<!-- /Logo -->
					<!-- <script>

						$(function() {
						  $("#query").autocomplete({
							source: "/search_auto/",
							select: function (event, ui) { //item selected
							  AutoCompleteSelectHandler(event, ui)
							},
							minLength: 2,
						  });
						});
					  
						function AutoCompleteSelectHandler(event, ui)
						{
						  var selectedObj = ui.item;
						}
					  
					</script> -->

					<!-- Search -->
					<div class="header-search">
						<form action="{% url 'search' %}" method="post">
							{% csrf_token %}
							<input id="query" name="query" class="input search-input" type="text" placeholder="Enter your keyword">
							<select name="catid" class="input search-categories">
								<option value="0">{% trans "All Categories" %}</option>
								{% load myapptags %}

								{% categorylist as categorie %}
								{% load mptt_tags %}

								{% recursetree categorie %}
									{% if not node.is_leaf_node %}
										<option value=" {{node.id}} ">{{node.titre}}</option>
									{% endif %}
									{% if not node.is_leaf_node %}
										<optgroup label="{{node.titre}}">
											{{ children }}
										</optgroup>
									{% endif %}
								{% endrecursetree %}
								
								
							</select>
							<button class="search-btn"><i class="fa fa-search"></i></button>
						</form>
					</div>
					<!-- /Search -->
				</div>
				<div class="pull-right">
					<ul class="header-btns">
						<!-- Account -->
						<li class="header-account dropdown default-dropdown">
							{% if user.id is not None%}
							<div class="dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="true">
								<div class="header-btns-icon">
									<img src="{{ request.session.userimage }}" style="height: 40px; width: 40px; border-radius: 10%;" alt="">
								</div>
								<strong class="text-uppercase">{{user.first_name}} <i class="fa fa-caret-down"></i></strong>
							</div>
							{% else %}
							<a href="{% url 'user:login' %}" class="text-uppercase">{% trans "Login" %}</a> / <a href="{% url 'user:signup' %}" class="text-uppercase">SingUp</a>
							{% endif %}
							<ul class="custom-menu">
								<li><a href="{% url 'user:moncompte' %}"><i class="fa fa-user-o"></i>{% trans "My Account" %}</a></li>
								<!-- <li><a href="/user/favorites"><i class="fa fa-heart-o"></i> "Mes favorites</a></li> -->
								<li><a href="{% url 'user:produits' %}"><i class="fa fa-exchange"></i> {% trans "Mes produits" %}</a></li>
								<li><a href="{% url 'user:comments' %}"><i class="fa fa-check"></i> {% trans "Comments" %}</a></li>
								<li><a href="{% url 'user:logout' %}"><i class="fa fa-unlock-alt"></i> {% trans "Logout" %}</a></li>
	
							</ul>
							

						</li>
						<!-- /Account -->

						<!-- Cart -->
						<li class="header-cart dropdown default-dropdown">
							<a href=" {% url 'shop-cart' %} " >
								<div class="header-btns-icon">
									<i class="fa fa-shopping-cart"></i>
									{% load myapptags %}
									{% shopcartcount user.id as cnt %}
									<span class="qty"> {{cnt}} </span>
								</div>
								<strong class="text-uppercase">{% trans "Mon Panier:" %}</strong>
								
								
							</a>
	
						</li>
						<!-- /Cart -->

						<!-- Mobile nav toggle-->
						<li class="nav-toggle">
							<button class="nav-toggle-btn main-btn icon-btn"><i class="fa fa-bars"></i></button>
						</li>
						<!-- / Mobile nav toggle -->
					</ul>
				</div>
			</div>
			<!-- header -->
		</div>
		<!-- container -->
	</header>
	<!-- /HEADER -->