e_shop/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns
from product.views import selectlanguage
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('selectlanguage', selectlanguage, name="selectlanguage"),
    path('i18n/', include("django.conf.urls.i18n")),
]

urlpatterns += i18n_patterns(
    path(_('admin/'), admin.site.urls),
	path('', include('home.urls')),
    path('', include('product.urls')),
    path('', include('user.urls')),
    path('', include('newsletters.urls')),
    #path('', include('newsletter.urls')),
    path('order/', include('order.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    prefix_default_language=False,
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

## APPLICATIONS

home/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
	path('', views.index, name = 'home'),
	path('about-us/', views.aboutus, name = 'about_us'),
	path('contact-us/', views.contactus, name = 'contact-us'),
	path('categorie/<int:id>/<slug:slug>', views.product_categorie, name = 'product_categorie'),
	path('search/', views.search, name = 'search'),
	path('shop-cart/', views.shop_cart, name = 'shop-cart'),
	path('search_auto/', views.search_auto, name = 'search_auto'),
	path('Articles/<int:id>/<slug:slug>', views.product_details, name = 'product_details'),
	path('faq', views.faq, name = 'faq'),

	path('ajaxcolor', views.ajaxcolors, name='ajaxcolor'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
	path('moncompte', views.index, name = 'moncompte'),
	path('login/', views.login_in, name = 'login'),
	path('logout/', views.logout_func, name = 'logout'),
	path('signup/', views.signup_form, name = 'signup'),
	path('Update-profile/', views.update_profile, name = 'Update-profile'),
	path('user/password', views.user_password, name = 'user_password'),
	#Panel url
	path('user/produits', views.user_orders, name = 'produits'),
	path('user/order-details/<int:id>', views.user_orderdetail, name = 'user_orderdetail'),
	path('orderproduct', views.user_orderproduct, name = 'orderproduct'),
	path('order-product-details/<int:id>/<int:oid>', views.user_order_product_detail, name = 'user_order_product_detail'),

	path('user/comments', views.user_comments, name = 'comments'),
	path('user/delete-comment/<int:id>', views.user_comments_delete, name = 'user_comments_delete'),
	
	
]

user/models.py
from django.db import models
from django.contrib.auth.models import User

#from home.models import Language
# Create your models here.
from django.utils.safestring import mark_safe


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address  = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')
    #language = models.ForeignKey(Language, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name+" "+ self.user.last_name+ " [" + self.user.username + "] "

    

    # def image_tag(self):
    #     return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    # image_tag.short_description= "Image"

user/forms.py
from django import forms
from django.forms import TextInput, EmailInput, FileInput, Select
from django.core.validators import validate_email
from django.contrib.auth.models import User
from user.models import UserProfile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class signUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='username')
    email = forms.EmailField(max_length=30, label='Email')
    first_name = forms.CharField(max_length=100, help_text='First Name', label='First_name')
    last_name = forms.CharField(max_length=100, help_text='Last Name', label='Last_name')

    class Meta:
        model = User
        fields = ('username','email','first_name','username','last_name','password1','password2',)

class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name', )
        widgets = {
            'username' : TextInput(attrs={'class':'input', 'placeholder':'username'}),
            'email' : EmailInput(attrs={'class':'input', 'placeholder':'email'}),
            'first_name' : TextInput(attrs={'class':'input', 'placeholder':'first_name'}),
            'last_name' : TextInput(attrs={'class':'input', 'placeholder':'last_name'}),
        }

CITY = [
    ('Bassam', 'Bassam'),
    ('Abidjan', 'Abidjan'),
    ('Korhogo', 'Korhogo'),
    ('Alepe', 'Alepe'),
    ('Boundiali', 'Boundiali'),
]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city', 'country', 'image')
        widgets = {
            'phone': TextInput(attrs={'class':'input', 'placeholder':'phone'}),
            'address': TextInput(attrs={'class':'input', 'placeholder':'address'}),
            'city': Select(attrs={'class':'input', 'placeholder':'city'}, choices=CITY),
            'country': TextInput(attrs={'class':'input', 'placeholder':'country'}),
            'image': FileInput(attrs={'class':'input', 'placeholder':'image'}),  
        }
   

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login,logout,update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect



from product.models import Category, Comment
from user.models import UserProfile
from order.models import Order, OrderProduit
from . forms import signUpForm, UserUpdateForm, ProfileUpdateForm

# Create your views here.
@login_required(login_url='/login') 
def index(request):
    #categorie = Category.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(user_id= current_user.id)
    
    
    context = {
        #'categorie':categorie,
        'profile':profile,
        }
    return render(request, 'user/user-profile.html', context)

def login_in(request):

    if request.method=='POST': #s'il y eu envoie de formulaire
        #On verifie le username et le password
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            current_user = request.user
            userprofile = UserProfile.objects.get(user_id=current_user.id)
            request.session['userimage'] = userprofile.image.url
            #I l'utilisateur est connecté on renvoie la page d'accueil
            messages.success(request, 'vous êtes bien connecté  '+ user.username )
            return HttpResponseRedirect('/')      
            
        else:
            messages.success(request, 'Login Error ! Nomutilisateur ou mot de passe incorrect')
            return HttpResponseRedirect('/login') #Renvoie tjrs la page de connexion
            
    #categorie = Category.objects.all()
    context = {
        #'categorie':categorie,
        }
    return render(request, 'user/login_form.html', context)

def logout_func(request):
    
    logout(request)
    return HttpResponseRedirect('/')

def signup_form(request):
    if request.method=='POST':
        form = signUpForm(request.POST)
        if form.is_valid():
            form.save()
            # username = form.cleaned_data['username']
            # email = form.cleaned_data['email']
            # first_name = form.cleaned_data['first_name']
            # last_name = form.cleaned_data['last_name']
            # password = form.cleaned_data['password']
            # User.objects.create_user(username=username, email=email,  first_name=first_name,
            #  last_name=last_name, password=password)

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            #Créer un profile par defaut
            current_user = request.user
            data = UserProfile()
            data.user_id = current_user.id
            data.image = 'images/users/user.jpg'
            data.save()

            messages.success(request, 'Votre compte a été crée avec succèss !!')
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect('/signup')
    
    else:
        form = signUpForm()
    #categorie = Category.objects.all()
    context = {
        #'categorie':categorie,
        'form':form,}
    return render(request, 'user/signup_form.html', context)
    

@login_required(login_url='/login')
def update_profile(request):
    if request.method=='POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Votre Profile a été modifier avec success !')
            return redirect('/moncompte')

    else:
        #categorie = Category.objects.all()
        user_form = UserUpdateForm( instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            #'categorie':categorie,
            'user_form':user_form,
            'profile_form':profile_form,
            }
        return render(request, 'user/update_profile.html', context)

@login_required(login_url='/login') 
def user_password(request):
    if request.method=='POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request,user)
            messages.success(request, 'Votre mode passe a été changé avec success')
            return HttpResponseRedirect('/Mon-Compte')
        else:
            messages.error(request, 'Vous avez saisi un mot de passe incorrect. <br>'+str(form.errors))
            return HttpResponseRedirect('/user/password')
    else:
        #categorie = Category.objects.all()
        form = PasswordChangeForm(request.user)
        context = {
            #'categorie':categorie,
            'form':form,
            
            }
        return render(request, 'user/user_password.html', context)

@login_required(login_url='/login') 
def user_orders(request):

    current_user = request.user
    orders = Order.objects.filter(user_id=current_user.id)

    #categorie = Category.objects.all()
    
    context = {
        #'categorie':categorie,
        'orders':orders,
        
        }
    return render(request, 'user/my-products.html', context)


@login_required(login_url='/login') 
def user_orderdetail(request, id):

    current_user = request.user
    orders = Order.objects.get(user_id=current_user.id, id=id)
    orderitems = OrderProduit.objects.filter(order_id=id)

    #categorie = Category.objects.all()
    
    context = {
        #'categorie':categorie,
        'orders':orders,
        'orderitems':orderitems,
        
        }
    return render(request, 'user/user-order-details.html', context)


@login_required(login_url='/login') 
def user_orderproduct(request):

    current_user = request.user
    order_product = OrderProduit.objects.filter(user_id=current_user.id)

    #categorie = Category.objects.all()
    
    context = {
        #'categorie':categorie,
        
        'order_product':order_product,
        
        }
    return render(request, 'user/user_order_products.html', context)

    
@login_required(login_url='/login') 
def user_order_product_detail(request, id, oid):
    current_user = request.user
    orders = Order.objects.get(user_id=current_user.id, id=oid)
    orderitems = OrderProduit.objects.filter(id=id, user_id=current_user.id)

    #categorie = Category.objects.all()
    
    context = {
        #'categorie':categorie,
        'orders':orders,
        'orderitems':orderitems,
        
        }
    return render(request, 'user/user-order-product-detail.html', context)


def user_comments(request):

    current_user = request.user
    comments = Comment.objects.filter(user_id=current_user.id)
    #categorie = Category.objects.all()
    
    context = {
        #'categorie':categorie,
        'comments':comments,
        
        }
    return render(request, 'user/user-comments.html', context)


@login_required(login_url='/login') 
def user_comments_delete(request, id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Votre message est supprmé avec success !! .')
    return HttpResponseRedirect('/user/comments')





    



    

    

templates/user/login_form.html
{% extends 'bases/base.html' %}

{% block title %} connection {% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keywords}} {% endblock %}

{% block sidebar %} {% include 'pages/sidebar.html' %} {% endblock  %}

{% block body %} 

     <!-- BREADCRUMB -->
     <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">connection </li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                
					<div class="col-md-6">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert-alert-{{message.tags}}" role="alert" style="color: green; font-style: italic;">
                                    {{message}}
                                </div>
                            {% endfor %}
					    {% endif %}
						<div class="billing-details">
							<div class="section-title">
								<h3 class="title">Se connecter </h3>
                            </div>
                            <form id="checkout-form" class="clearfix" method="post" action="  ">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input class="input" type="text" name="username" placeholder="Username" required>
                                </div>
                                <div class="form-group">
                                    <input class="input" type="password" name="password" placeholder="Your password" required>
                                </div>
                                
                                    <input  type="submit"  value="Envoyer">
                               
                            </form>
						</div>
                    </div>

                    <div class="col-md-6">
                        <div class="section-title">
                            <h3 class="title">Inscription</h3>
                        </div>
                        {% if messages %}
                            {% for messag in messages %}
                                <div class="alert-alert-{{messag.tags}}" role="alert" style="color: green; font-style: italic;">
                                    {{messag}}
                                </div>
                            {% endfor %}
					    {% endif %}
						<form action="" method="post">
                            {% csrf_token %}

                            <!-- {{ form.as_p}} -->
                            {% for field in form %}
                            <p>
                                {{ field.label_tag }} <br>
                                {{ field }}
                                {% if field.help_text %}
                                <small style="...">{{ field.help_text}}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                    <p style="...">{{error}}</p>
                                {% endfor %}
                            </p>
                            {% endfor %} 
                            
                            <button type="submit">Singn Up</button>
                        </form>
					</div>
                    
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock  %}

templates/user/my-products.html
{% extends 'bases/base.html' %}

{% block title %}  Mes produits {% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keywords}} {% endblock %}

{% block sidebar %} {% include 'pages/sidebar.html' %} {% endblock  %}

{% block body %} 

     <!-- BREADCRUMB -->
     <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">Mes produits</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-3">
                    {% include 'user/user-panel.html' %}
                </div>

                <div class="col-md-9">
                    <div class="section-title">
                        <h3>Mes produits</h3>
                    </div>
                    <table class="shopping-cart-table table">
                        <thead>
                            <tr>
                                <th class="text-left">ID</th>
                                <th class="text-left">Nom</th>
                                <th class="text-left">Prenom</th>
                                <th class="text-left">Total</th>
                                <th class="text-left">Status</th>
                                <th class="text-left">Date</th>
                                <th class="text-right">Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for sp in orders %}
                            <tr>
                                <th class="text-left"> {{sp.id}} </th>
                                <th class="text-left">{{sp.first_name}}</th>
                                <th class="text-left">{{sp.last_name}}</th>
                                <th class="text-left">{{sp.total}}</th>
                                <th class="text-left">{{sp.status}}</th>
                                <th class="text-left">{{sp.date_add}}</th>
                                <th class="text-right"> <a class="primary-btn" href="/user/order-details/{{sp.id}}">Details</a></th>
                            {% endfor %}
                            
                    </table>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock  %}

templates/user/signup_form.html
{% extends 'bases/base.html' %}

{% block title %} Inscription {% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keywords}} {% endblock %}

{% block sidebar %} {% include 'pages/sidebar.html' %} {% endblock  %}

{% block body %} 

     <!-- BREADCRUMB -->
     <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">Inscription  </li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                
					<div class="col-md-6">
                        <div class="section-title">
                            <h3 class="title">Inscription</h3>
                        </div>
                        {% if messages %}
                            {% for messag in messages %}
                                <div class="alert-alert-{{messag.tags}}" role="alert" style="color: green; font-style: italic;">
                                    {{messag}}
                                </div>
                            {% endfor %}
					    {% endif %}
						<form action="" method="post">
                            {% csrf_token %}

                            <!-- {{ form.as_p}} -->
                            {% for field in form %}
                            <p>
                                {{ field.label_tag }} <br>
                                {{ field }}
                                {% if field.help_text %}
                                <small style="...">{{ field.help_text}}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                    <p style="...">{{error}}</p>
                                {% endfor %}
                            </p>
                            {% endfor %} 
                            
                            <button type="submit">Singn Up</button>
                        </form>
					</div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock  %}

templates/user/update_profile.html
{% extends 'bases/base.html' %}

{% block title %} {{user.first_name}} Profile Update {% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keywords}} {% endblock %}

{% block sidebar %} {% include 'pages/sidebar.html' %} {% endblock  %}

{% block body %} 

     <!-- BREADCRUMB -->
     <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">Modifier mon profile </li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-3">
                    {% include 'user/user-panel.html' %}
                </div>
                <div class="col-md-9">
                    <div class="billing-details">
                        <div class="section-title">
                            <h3 class="title">Modifier mon profile</h3>
                        </div>
                    </div>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            {{ user_form.as_p }}
                            {{ profile_form.as_p }}
                        </fieldset>
                        <div class="form-group">
                            <button type="submit" class="primary-btn">Modifier</button>
                        </div>
                    </form>
                </div>
                
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock  %}

templates/user/user-panel.html
   
   
   <div class="billing-details">
        <div class="section-title">
            <h3 class="title">Mon panier </h3>
        </div>
        <div class="aside">

            <ul class="list-links">
                <li><a href="{% url 'user:moncompte' %}"><i class="fa fa-user-o"></i> My Account</a></li>
                <li><a href="/user/favorites"><i class="fa fa-heart-o"></i> Mes Favories</a></li>
                <li><a href="{% url 'user:orderproduct' %}"><i class="fa fa-exchange"></i> Mes produits commandés</a></li>
                <li><a href="/user/produits"><i class="fa fa-exchange"></i> Mes produits</a></li>
                <li><a href="/user/comments"><i class="fa fa-check"></i> commentaire</a></li>
                <li><a href="/logout"><i class="fa fa-unlock-alt"></i> Logout</a></li>
            </ul>

            
        </div>
        
    </div>

templates/user/user-profile.html
{% extends 'bases/base.html' %}

{% block title %} {{user.first_name}} Profile {% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keywords}} {% endblock %}

{% block sidebar %} {% include 'pages/sidebar.html' %} {% endblock  %}

{% block body %} 

     <!-- BREADCRUMB -->
     <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">Mon Compte </li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-3">
                    {% include 'user/user-panel.html' %}
                </div>
                <div class="col-md-9">
                    <div class="billing-details">
                        <div class="section-title">
                            <h3 class="title">Mes Informations</h3>
                        </div>

                        <table class="shopping-cart-table table">
                            <tr>
                                <th class="text-left">
                                    <a href=" {% url 'user:Update-profile' %} " class="primary-btn">Modifier Votre profile</a>
                                    <a href="/user/password" class="primary-btn">Changer Votre mot de passe</a>
                                    
                                </th>
                                <td><img src=" {{profile.image.url}} " alt="" style="height: 150px; width: 120px; border-radius: 20px;"></td>
                                <tr>
                                    <th class="text-left">Nom & Prénom</th>
                                    <td class="text-left">{{user.first_name}} {{user.last_name}}</td>
                                </tr>
                                <tr>
                                    <th class="text-left">Email</th>
                                    <td class="text-left">{{profile.user.email}}</td>
                                </tr>
                                <tr>
                                    <th class="text-left">Téléphone </th>
                                    <td class="text-left">{{profile.phone}}</td>
                                </tr>
                                <tr>
                                    <th class="text-left">Address </th>
                                    <td class="text-left">{{profile.address}}</td>
                                </tr>
                                <tr>
                                    <th class="text-left">Ville </th>
                                    <td class="text-left">{{profile.city}}</td>
                                </tr>
                                <tr>
                                    <th class="text-left">Pays </th>
                                    <td class="text-left">{{profile.country}}</td>
                                </tr>
                               
                            </tr>
                        </table>
                    </div>
                </div>
                
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock  %}

templates/user/user_password.html
{% extends 'bases/base.html' %}

{% block title %} User Change password{% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keywords}} {% endblock %}

{% block sidebar %} {% include 'pages/sidebar.html' %} {% endblock  %}

{% block body %} 

     <!-- BREADCRUMB -->
     <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">Change password </li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-4">
                    {% include 'user/user-panel.html' %}
                </div>
                <div class="col-md-8">
                    <div class="section-title">
                        <h3 class="title">Change password</h3>
                    </div>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert-alert-{{messag.tags}}" role="alert" style="color: green; font-style: italic;">
                                {{message|safe}}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form action="" method="post">
                        {% csrf_token %}

                        <!-- {{ form.as_p}} -->
                        {% for field in form %}
                        <p>
                            {{ field.label_tag }} <br>
                            {{ field }}
                            {% if field.help_text %}
                            <small style="...">{{ field.help_text}}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <p style="...">{{error}}</p>
                            {% endfor %}
                        </p>
                        {% endfor %} 
                        
                        <button class="primary-btn" type="submit">Enregister</button>
                    </form>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock  %}